DATASET AGGREGATION

In [21]:
import pandas as pd

In [22]:
setA = r'data\interim\part_processA.csv'
setB = r'data\interim\part_processB.csv'

In [23]:
dfA = pd.read_csv(setA)
dfB = pd.read_csv(setB)

dfA.drop(columns = ['Unnamed: 0'], inplace = True)
dfB.drop(columns = ['Unnamed: 0'], inplace = True)

###### ONE PATIENT = ONE ROW

In [24]:
dfA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790215 entries, 0 to 790214
Data columns (total 35 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   HR           729026 non-null  float64
 1   O2Sat        695136 non-null  float64
 2   Temp         266901 non-null  float64
 3   SBP          670014 non-null  float64
 4   MAP          709357 non-null  float64
 5   DBP          409918 non-null  float64
 6   Resp         712957 non-null  float64
 7   BaseExcess   82381 non-null   float64
 8   HCO3         63617 non-null   float64
 9   FiO2         112155 non-null  float64
 10  pH           90615 non-null   float64
 11  PaCO2        69288 non-null   float64
 12  BUN          64476 non-null   float64
 13  Calcium      39318 non-null   float64
 14  Chloride     65777 non-null   float64
 15  Creatinine   52487 non-null   float64
 16  Glucose      96656 non-null   float64
 17  Lactate      27143 non-null   float64
 18  Magnesium    61481 non-null   float64
 19  Phosphate    39896 non-null   float64
 20  Potassium    85836 non-null   float64
 21  Hct          93058 non-null   float64
 22  Hgb          69821 non-null   float64
 23  PTT          38306 non-null   float64
 24  WBC          59348 non-null   float64
 25  Fibrinogen   6030 non-null    float64
 26  Platelets    51499 non-null   float64
 27  Age          790215 non-null  float64
 28  Gender       790215 non-null  int64
 29  Unit1        404050 non-null  float64
 30  Unit2        404050 non-null  float64
 31  HospAdmTime  790207 non-null  float64
 32  ICULOS       790215 non-null  int64
 33  SepsisLabel  790215 non-null  int64
 34  patient_id   790215 non-null  object
dtypes: float64(31), int64(3), object(1)
memory usage: 211.0+ MB

In [25]:
dfB.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 790215 entries, 0 to 790214
Data columns (total 35 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   HR           729026 non-null  float64
 1   O2Sat        695136 non-null  float64
 2   Temp         266901 non-null  float64
 3   SBP          670014 non-null  float64
 4   MAP          709357 non-null  float64
 5   DBP          409918 non-null  float64
 6   Resp         712957 non-null  float64
 7   BaseExcess   82381 non-null   float64
 8   HCO3         63617 non-null   float64
 9   FiO2         112155 non-null  float64
 10  pH           90615 non-null   float64
 11  PaCO2        69288 non-null   float64
 12  BUN          64476 non-null   float64
 13  Calcium      39318 non-null   float64
 14  Chloride     65777 non-null   float64
 15  Creatinine   52487 non-null   float64
 16  Glucose      96656 non-null   float64
 17  Lactate      27143 non-null   float64
 18  Magnesium    61481 non-null   float64
 19  Phosphate    39896 non-null   float64
 20  Potassium    85836 non-null   float64
 21  Hct          93058 non-null   float64
 22  Hgb          69821 non-null   float64
 23  PTT          38306 non-null   float64
 24  WBC          59348 non-null   float64
 25  Fibrinogen   6030 non-null    float64
 26  Platelets    51499 non-null   float64
 27  Age          790215 non-null  float64
 28  Gender       790215 non-null  int64
 29  Unit1        404050 non-null  float64
 30  Unit2        404050 non-null  float64
 31  HospAdmTime  790207 non-null  float64
 32  ICULOS       790215 non-null  int64
 33  SepsisLabel  790215 non-null  int64
 34  patient_id   790215 non-null  object
dtypes: float64(31), int64(3), object(1)
memory usage: 211.0+ MB

In [30]:
vital_signs = ['HR', 'O2Sat', 'Temp', 'SBP', 'MAP', 'DBP', 'Resp']
metabolic = ['BaseExcess', 'HCO3', 'Lactate', 'Glucose']
kidney_function = ['BUN', 'Creatinine', 'Calcium', 'Chloride', 'Magnesium', 'Phosphate', 'Potassium']
hematology = ['Hct', 'Hgb', 'WBC', 'Platelets', 'PTT', 'Fibrinogen']
blood_gas_function = ['FiO2', 'pH', 'PaCO2']
demographics = ['Age', 'Gender', 'HospAdmTime', 'Unit1', 'Unit2']
time_label = ['ICULOS', 'SepsisLabel', 'patient_id']

In [34]:
agg_col = vital_signs + metabolic + kidney_function + hematology + blood_gas_function

agg_dict = {col : ['mean', 'std', 'max', 'min', 'count'] for col in agg_col
       }
agg.update({col : ['first'] for col in demographics})
agg.update({'ICULOS' : ['max']})
agg.update({'SepsisLabel' : ['max']})

In [35]:
agg_dict

{'HR': ['mean', 'std', 'max', 'min', 'count'],
 'O2Sat': ['mean', 'std', 'max', 'min', 'count'],
 'Temp': ['mean', 'std', 'max', 'min', 'count'],
 'SBP': ['mean', 'std', 'max', 'min', 'count'],
 'MAP': ['mean', 'std', 'max', 'min', 'count'],
 'DBP': ['mean', 'std', 'max', 'min', 'count'],
 'Resp': ['mean', 'std', 'max', 'min', 'count'],
 'BaseExcess': ['mean', 'std', 'max', 'min', 'count'],
 'HCO3': ['mean', 'std', 'max', 'min', 'count'],
 'Lactate': ['mean', 'std', 'max', 'min', 'count'],
 'Glucose': ['mean', 'std', 'max', 'min', 'count'],
 'BUN': ['mean', 'std', 'max', 'min', 'count'],
 'Creatinine': ['mean', 'std', 'max', 'min', 'count'],
 'Calcium': ['mean', 'std', 'max', 'min', 'count'],
 'Chloride': ['mean', 'std', 'max', 'min', 'count'],
 'Magnesium': ['mean', 'std', 'max', 'min', 'count'],
 'Phosphate': ['mean', 'std', 'max', 'min', 'count'],
 'Potassium': ['mean', 'std', 'max', 'min', 'count'],
 'Hct': ['mean', 'std', 'max', 'min', 'count'],
 'Hgb': ['mean', 'std', 'max', 'min', 'count'],
 'WBC': ['mean', 'std', 'max', 'min', 'count'],
 'Platelets': ['mean', 'std', 'max', 'min', 'count'],
 'PTT': ['mean', 'std', 'max', 'min', 'count'],
 'Fibrinogen': ['mean', 'std', 'max', 'min', 'count'],
 'FiO2': ['mean', 'std', 'max', 'min', 'count'],
 'pH': ['mean', 'std', 'max', 'min', 'count'],
 'PaCO2': ['mean', 'std', 'max', 'min', 'count']}

In [37]:
dfA_final = dfA.groupby('patient_id').agg(agg_dict)

In [38]:
dfA_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20336 entries, p000001.psv to p020643.psv
Columns: 135 entries, ('HR', 'mean') to ('PaCO2', 'count')
dtypes: float64(108), int64(27)
memory usage: 21.1+ MB

In [ ]:
dfA_final.columns = ['_'.join(col) for col in dfA_final.columns] #flattening the name

# the old name format is the nested column form that comes out after groupby().agg(), like:

# ('HR', 'mean')

# The new one is the flattened version, like:

# HR_mean

In [41]:
dfA_final

,HR_mean,HR_std,HR_max,HR_min,HR_count,O2Sat_mean,O2Sat_std,O2Sat_max,O2Sat_min,O2Sat_count,...,pH_mean,pH_std,pH_max,pH_min,pH_count,PaCO2_mean,PaCO2_std,PaCO2_max,PaCO2_min,PaCO2_count
patient_id,,,,,,,,,,,,,,,,,,,,,
p000001.psv,101.571429,9.594378,117.0,76.0,49,91.477273,3.460667,100.0,85.0,44,...,7.347143,0.031472,7.40,7.31,7,95.333333,6.022181,100.0,86.0,6
p000002.psv,60.954545,8.144395,94.0,54.0,22,97.000000,2.138090,100.0,94.0,22,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p000003.psv,79.611111,6.714036,93.0,68.0,45,95.431818,1.655122,99.0,91.0,44,...,7.496667,0.011547,7.51,7.49,3,39.500000,2.121320,41.0,38.0,2
p000004.psv,102.444444,6.337212,113.0,93.0,27,98.203704,1.449531,100.0,95.5,27,...,7.390000,0.026458,7.41,7.36,3,43.000000,2.828427,45.0,41.0,2
p000005.psv,73.916667,7.586697,88.0,61.0,24,97.500000,0.741620,99.0,96.0,21,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
p020639.psv,87.420000,12.475543,120.0,74.0,25,98.940000,0.982344,100.0,97.0,25,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p020640.psv,80.920000,7.425575,96.0,71.0,25,95.620000,1.861227,100.0,93.0,25,...,7.358333,0.059470,7.43,7.26,6,37.900000,3.577709,44.0,35.0,5
p020641.psv,85.900000,7.281194,101.5,76.0,20,97.023810,1.874008,99.0,94.0,21,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p020642.psv,96.525000,11.602359,130.0,79.0,40,99.512821,0.942332,100.0,96.0,39,...,7.450000,0.000000,7.45,7.45,2,34.000000,NaN,34.0,34.0,1
p020643.psv,94.448276,15.204760,140.0,79.0,29,97.178571,2.211980,100.0,88.0,28,...,7.374000,0.124820,7.48,7.16,5,45.200000,12.657014,67.0,34.0,5

In [ ]:
dfA_final.info(verbose=True, show_counts=True) #verbose means “show the full summary instead of a shortened one.” show_counts means “show how many non-missing values each column has.”

<class 'pandas.core.frame.DataFrame'>
Index: 20336 entries, p000001.psv to p020643.psv
Data columns (total 135 columns):
 #    Column                           Non-Null Count  Dtype
---   ------                           --------------  -----
 0    H_R___m_e_a_n                    20335 non-null  float64
 1    H_R___s_t_d                      20330 non-null  float64
 2    H_R___m_a_x                      20335 non-null  float64
 3    H_R___m_i_n                      20335 non-null  float64
 4    H_R___c_o_u_n_t                  20336 non-null  int64
 5    O_2_S_a_t___m_e_a_n              20324 non-null  float64
 6    O_2_S_a_t___s_t_d                20314 non-null  float64
 7    O_2_S_a_t___m_a_x                20324 non-null  float64
 8    O_2_S_a_t___m_i_n                20324 non-null  float64
 9    O_2_S_a_t___c_o_u_n_t            20336 non-null  int64
 10   T_e_m_p___m_e_a_n                20101 non-null  float64
 11   T_e_m_p___s_t_d                  19861 non-null  float64
 12   T_e_m_p___m_a_x                  20101 non-null  float64
 13   T_e_m_p___m_i_n                  20101 non-null  float64
 14   T_e_m_p___c_o_u_n_t              20336 non-null  int64
 15   S_B_P___m_e_a_n                  20078 non-null  float64
 16   S_B_P___s_t_d                    20018 non-null  float64
 17   S_B_P___m_a_x                    20078 non-null  float64
 18   S_B_P___m_i_n                    20078 non-null  float64
 19   S_B_P___c_o_u_n_t                20336 non-null  int64
 20   M_A_P___m_e_a_n                  20334 non-null  float64
 21   M_A_P___s_t_d                    20326 non-null  float64
 22   M_A_P___m_a_x                    20334 non-null  float64
 23   M_A_P___m_i_n                    20334 non-null  float64
 24   M_A_P___c_o_u_n_t                20336 non-null  int64
 25   D_B_P___m_e_a_n                  12952 non-null  float64
 26   D_B_P___s_t_d                    12773 non-null  float64
 27   D_B_P___m_a_x                    12952 non-null  float64
 28   D_B_P___m_i_n                    12952 non-null  float64
 29   D_B_P___c_o_u_n_t                20336 non-null  int64
 30   R_e_s_p___m_e_a_n                20308 non-null  float64
 31   R_e_s_p___s_t_d                  20285 non-null  float64
 32   R_e_s_p___m_a_x                  20308 non-null  float64
 33   R_e_s_p___m_i_n                  20308 non-null  float64
 34   R_e_s_p___c_o_u_n_t              20336 non-null  int64
 35   B_a_s_e_E_x_c_e_s_s___m_e_a_n    12652 non-null  float64
 36   B_a_s_e_E_x_c_e_s_s___s_t_d      10924 non-null  float64
 37   B_a_s_e_E_x_c_e_s_s___m_a_x      12652 non-null  float64
 38   B_a_s_e_E_x_c_e_s_s___m_i_n      12652 non-null  float64
 39   B_a_s_e_E_x_c_e_s_s___c_o_u_n_t  20336 non-null  int64
 40   H_C_O_3___m_e_a_n                19801 non-null  float64
 41   H_C_O_3___s_t_d                  15941 non-null  float64
 42   H_C_O_3___m_a_x                  19801 non-null  float64
 43   H_C_O_3___m_i_n                  19801 non-null  float64
 44   H_C_O_3___c_o_u_n_t              20336 non-null  int64
 45   L_a_c_t_a_t_e___m_e_a_n          7733 non-null   float64
 46   L_a_c_t_a_t_e___s_t_d            5090 non-null   float64
 47   L_a_c_t_a_t_e___m_a_x            7733 non-null   float64
 48   L_a_c_t_a_t_e___m_i_n            7733 non-null   float64
 49   L_a_c_t_a_t_e___c_o_u_n_t        20336 non-null  int64
 50   G_l_u_c_o_s_e___m_e_a_n          19929 non-null  float64
 51   G_l_u_c_o_s_e___s_t_d            16572 non-null  float64
 52   G_l_u_c_o_s_e___m_a_x            19929 non-null  float64
 53   G_l_u_c_o_s_e___m_i_n            19929 non-null  float64
 54   G_l_u_c_o_s_e___c_o_u_n_t        20336 non-null  int64
 55   B_U_N___m_e_a_n                  19909 non-null  float64
 56   B_U_N___s_t_d                    16109 non-null  float64
 57   B_U_N___m_a_x                    19909 non-null  float64
 58   B_U_N___m_i_n                    19909 non-null  float64
 59   B_U_N___c_o_u_n_t                20336 non-null  int64
 60   C_r_e_a_t_i_n_i_n_e___m_e_a_n    19875 non-null  float64
 61   C_r_e_a_t_i_n_i_n_e___s_t_d      14975 non-null  float64
 62   C_r_e_a_t_i_n_i_n_e___m_a_x      19875 non-null  float64
 63   C_r_e_a_t_i_n_i_n_e___m_i_n      19875 non-null  float64
 64   C_r_e_a_t_i_n_i_n_e___c_o_u_n_t  20336 non-null  int64
 65   C_a_l_c_i_u_m___m_e_a_n          16547 non-null  float64
 66   C_a_l_c_i_u_m___s_t_d            10616 non-null  float64
 67   C_a_l_c_i_u_m___m_a_x            16547 non-null  float64
 68   C_a_l_c_i_u_m___m_i_n            16547 non-null  float64
 69   C_a_l_c_i_u_m___c_o_u_n_t        20336 non-null  int64
 70   C_h_l_o_r_i_d_e___m_e_a_n        19794 non-null  float64
 71   C_h_l_o_r_i_d_e___s_t_d          15938 non-null  float64
 72   C_h_l_o_r_i_d_e___m_a_x          19794 non-null  float64
 73   C_h_l_o_r_i_d_e___m_i_n          19794 non-null  float64
 74   C_h_l_o_r_i_d_e___c_o_u_n_t      20336 non-null  int64
 75   M_a_g_n_e_s_i_u_m___m_e_a_n      18948 non-null  float64
 76   M_a_g_n_e_s_i_u_m___s_t_d        14870 non-null  float64
 77   M_a_g_n_e_s_i_u_m___m_a_x        18948 non-null  float64
 78   M_a_g_n_e_s_i_u_m___m_i_n        18948 non-null  float64
 79   M_a_g_n_e_s_i_u_m___c_o_u_n_t    20336 non-null  int64
 80   P_h_o_s_p_h_a_t_e___m_e_a_n      16686 non-null  float64
 81   P_h_o_s_p_h_a_t_e___s_t_d        10766 non-null  float64
 82   P_h_o_s_p_h_a_t_e___m_a_x        16686 non-null  float64
 83   P_h_o_s_p_h_a_t_e___m_i_n        16686 non-null  float64
 84   P_h_o_s_p_h_a_t_e___c_o_u_n_t    20336 non-null  int64
 85   P_o_t_a_s_s_i_u_m___m_e_a_n      19903 non-null  float64
 86   P_o_t_a_s_s_i_u_m___s_t_d        16904 non-null  float64
 87   P_o_t_a_s_s_i_u_m___m_a_x        19903 non-null  float64
 88   P_o_t_a_s_s_i_u_m___m_i_n        19903 non-null  float64
 89   P_o_t_a_s_s_i_u_m___c_o_u_n_t    20336 non-null  int64
 90   H_c_t___m_e_a_n                  19972 non-null  float64
 91   H_c_t___s_t_d                    17365 non-null  float64
 92   H_c_t___m_a_x                    19972 non-null  float64
 93   H_c_t___m_i_n                    19972 non-null  float64
 94   H_c_t___c_o_u_n_t                20336 non-null  int64
 95   H_g_b___m_e_a_n                  19829 non-null  float64
 96   H_g_b___s_t_d                    16079 non-null  float64
 97   H_g_b___m_a_x                    19829 non-null  float64
 98   H_g_b___m_i_n                    19829 non-null  float64
 99   H_g_b___c_o_u_n_t                20336 non-null  int64
 100  W_B_C___m_e_a_n                  19711 non-null  float64
 101  W_B_C___s_t_d                    15410 non-null  float64
 102  W_B_C___m_a_x                    19711 non-null  float64
 103  W_B_C___m_i_n                    19711 non-null  float64
 104  W_B_C___c_o_u_n_t                20336 non-null  int64
 105  P_l_a_t_e_l_e_t_s___m_e_a_n      19751 non-null  float64
 106  P_l_a_t_e_l_e_t_s___s_t_d        14789 non-null  float64
 107  P_l_a_t_e_l_e_t_s___m_a_x        19751 non-null  float64
 108  P_l_a_t_e_l_e_t_s___m_i_n        19751 non-null  float64
 109  P_l_a_t_e_l_e_t_s___c_o_u_n_t    20336 non-null  int64
 110  P_T_T___m_e_a_n                  15840 non-null  float64
 111  P_T_T___s_t_d                    9368 non-null   float64
 112  P_T_T___m_a_x                    15840 non-null  float64
 113  P_T_T___m_i_n                    15840 non-null  float64
 114  P_T_T___c_o_u_n_t                20336 non-null  int64
 115  F_i_b_r_i_n_o_g_e_n___m_e_a_n    2567 non-null   float64
 116  F_i_b_r_i_n_o_g_e_n___s_t_d      1170 non-null   float64
 117  F_i_b_r_i_n_o_g_e_n___m_a_x      2567 non-null   float64
 118  F_i_b_r_i_n_o_g_e_n___m_i_n      2567 non-null   float64
 119  F_i_b_r_i_n_o_g_e_n___c_o_u_n_t  20336 non-null  int64
 120  F_i_O_2___m_e_a_n                11987 non-null  float64
 121  F_i_O_2___s_t_d                  11196 non-null  float64
 122  F_i_O_2___m_a_x                  11987 non-null  float64
 123  F_i_O_2___m_i_n                  11987 non-null  float64
 124  F_i_O_2___c_o_u_n_t              20336 non-null  int64
 125  p_H___m_e_a_n                    13181 non-null  float64
 126  p_H___s_t_d                      11268 non-null  float64
 127  p_H___m_a_x                      13181 non-null  float64
 128  p_H___m_i_n                      13181 non-null  float64
 129  p_H___c_o_u_n_t                  20336 non-null  int64
 130  P_a_C_O_2___m_e_a_n              12577 non-null  float64
 131  P_a_C_O_2___s_t_d                10459 non-null  float64
 132  P_a_C_O_2___m_a_x                12577 non-null  float64
 133  P_a_C_O_2___m_i_n                12577 non-null  float64
 134  P_a_C_O_2___c_o_u_n_t            20336 non-null  int64
dtypes: float64(108), int64(27)
memory usage: 21.1+ MB

MAKING THE NAMES VISUALLY APPEALING

In [49]:
rename_dictionary = {
    'H_R___m_e_a_n': 'HR_mean',
    'H_R___s_t_d': 'HR_std',
    'H_R___m_a_x': 'HR_max',
    'H_R___m_i_n': 'HR_min',
    'H_R___c_o_u_n_t': 'HR_count',
    'O_2_S_a_t___m_e_a_n': 'O2Sat_mean',
    'O_2_S_a_t___s_t_d': 'O2Sat_std',
    'O_2_S_a_t___m_a_x': 'O2Sat_max',
    'O_2_S_a_t___m_i_n': 'O2Sat_min',
    'O_2_S_a_t___c_o_u_n_t': 'O2Sat_count',
    'T_e_m_p___m_e_a_n': 'Temp_mean',
    'T_e_m_p___s_t_d': 'Temp_std',
    'T_e_m_p___m_a_x': 'Temp_max',
    'T_e_m_p___m_i_n': 'Temp_min',
    'T_e_m_p___c_o_u_n_t': 'Temp_count',
    'S_B_P___m_e_a_n': 'SBP_mean',
    'S_B_P___s_t_d': 'SBP_std',
    'S_B_P___m_a_x': 'SBP_max',
    'S_B_P___m_i_n': 'SBP_min',
    'S_B_P___c_o_u_n_t': 'SBP_count',
    'M_A_P___m_e_a_n': 'MAP_mean',
    'M_A_P___s_t_d': 'MAP_std',
    'M_A_P___m_a_x': 'MAP_max',
    'M_A_P___m_i_n': 'MAP_min',
    'M_A_P___c_o_u_n_t': 'MAP_count',
    'D_B_P___m_e_a_n': 'DBP_mean',
    'D_B_P___s_t_d': 'DBP_std',
    'D_B_P___m_a_x': 'DBP_max',
    'D_B_P___m_i_n': 'DBP_min',
    'D_B_P___c_o_u_n_t': 'DBP_count',
    'R_e_s_p___m_e_a_n': 'Resp_mean',
    'R_e_s_p___s_t_d': 'Resp_std',
    'R_e_s_p___m_a_x': 'Resp_max',
    'R_e_s_p___m_i_n': 'Resp_min',
    'R_e_s_p___c_o_u_n_t': 'Resp_count',
    'B_a_s_e_E_x_c_e_s_s___m_e_a_n': 'BaseExcess_mean',
    'B_a_s_e_E_x_c_e_s_s___s_t_d': 'BaseExcess_std',
    'B_a_s_e_E_x_c_e_s_s___m_a_x': 'BaseExcess_max',
    'B_a_s_e_E_x_c_e_s_s___m_i_n': 'BaseExcess_min',
    'B_a_s_e_E_x_c_e_s_s___c_o_u_n_t': 'BaseExcess_count',
    'H_C_O_3___m_e_a_n': 'HCO3_mean',
    'H_C_O_3___s_t_d': 'HCO3_std',
    'H_C_O_3___m_a_x': 'HCO3_max',
    'H_C_O_3___m_i_n': 'HCO3_min',
    'H_C_O_3___c_o_u_n_t': 'HCO3_count',
    'L_a_c_t_a_t_e___m_e_a_n': 'Lactate_mean',
    'L_a_c_t_a_t_e___s_t_d': 'Lactate_std',
    'L_a_c_t_a_t_e___m_a_x': 'Lactate_max',
    'L_a_c_t_a_t_e___m_i_n': 'Lactate_min',
    'L_a_c_t_a_t_e___c_o_u_n_t': 'Lactate_count',
    'G_l_u_c_o_s_e___m_e_a_n': 'Glucose_mean',
    'G_l_u_c_o_s_e___s_t_d': 'Glucose_std',
    'G_l_u_c_o_s_e___m_a_x': 'Glucose_max',
    'G_l_u_c_o_s_e___m_i_n': 'Glucose_min',
    'G_l_u_c_o_s_e___c_o_u_n_t': 'Glucose_count',
    'B_U_N___m_e_a_n': 'BUN_mean',
    'B_U_N___s_t_d': 'BUN_std',
    'B_U_N___m_a_x': 'BUN_max',
    'B_U_N___m_i_n': 'BUN_min',
    'B_U_N___c_o_u_n_t': 'BUN_count',
    'C_r_e_a_t_i_n_i_n_e___m_e_a_n': 'Creatinine_mean',
    'C_r_e_a_t_i_n_i_n_e___s_t_d': 'Creatinine_std',
    'C_r_e_a_t_i_n_i_n_e___m_a_x': 'Creatinine_max',
    'C_r_e_a_t_i_n_i_n_e___m_i_n': 'Creatinine_min',
    'C_r_e_a_t_i_n_i_n_e___c_o_u_n_t': 'Creatinine_count',
    'C_a_l_c_i_u_m___m_e_a_n': 'Calcium_mean',
    'C_a_l_c_i_u_m___s_t_d': 'Calcium_std',
    'C_a_l_c_i_u_m___m_a_x': 'Calcium_max',
    'C_a_l_c_i_u_m___m_i_n': 'Calcium_min',
    'C_a_l_c_i_u_m___c_o_u_n_t': 'Calcium_count',
    'C_h_l_o_r_i_d_e___m_e_a_n': 'Chloride_mean',
    'C_h_l_o_r_i_d_e___s_t_d': 'Chloride_std',
    'C_h_l_o_r_i_d_e___m_a_x': 'Chloride_max',
    'C_h_l_o_r_i_d_e___m_i_n': 'Chloride_min',
    'C_h_l_o_r_i_d_e___c_o_u_n_t': 'Chloride_count',
    'M_a_g_n_e_s_i_u_m___m_e_a_n': 'Magnesium_mean',
    'M_a_g_n_e_s_i_u_m___s_t_d': 'Magnesium_std',
    'M_a_g_n_e_s_i_u_m___m_a_x': 'Magnesium_max',
    'M_a_g_n_e_s_i_u_m___m_i_n': 'Magnesium_min',
    'M_a_g_n_e_s_i_u_m___c_o_u_n_t': 'Magnesium_count',
    'P_h_o_s_p_h_a_t_e___m_e_a_n': 'Phosphate_mean',
    'P_h_o_s_p_h_a_t_e___s_t_d': 'Phosphate_std',
    'P_h_o_s_p_h_a_t_e___m_a_x': 'Phosphate_max',
    'P_h_o_s_p_h_a_t_e___m_i_n': 'Phosphate_min',
    'P_h_o_s_p_h_a_t_e___c_o_u_n_t': 'Phosphate_count',
    'P_o_t_a_s_s_i_u_m___m_e_a_n': 'Potassium_mean',
    'P_o_t_a_s_s_i_u_m___s_t_d': 'Potassium_std',
    'P_o_t_a_s_s_i_u_m___m_a_x': 'Potassium_max',
    'P_o_t_a_s_s_i_u_m___m_i_n': 'Potassium_min',
    'P_o_t_a_s_s_i_u_m___c_o_u_n_t': 'Potassium_count',
    'H_c_t___m_e_a_n': 'Hct_mean',
    'H_c_t___s_t_d': 'Hct_std',
    'H_c_t___m_a_x': 'Hct_max',
    'H_c_t___m_i_n': 'Hct_min',
    'H_c_t___c_o_u_n_t': 'Hct_count',
    'H_g_b___m_e_a_n': 'Hgb_mean',
    'H_g_b___s_t_d': 'Hgb_std',
    'H_g_b___m_a_x': 'Hgb_max',
    'H_g_b___m_i_n': 'Hgb_min',
    'H_g_b___c_o_u_n_t': 'Hgb_count',
    'W_B_C___m_e_a_n': 'WBC_mean',
    'W_B_C___s_t_d': 'WBC_std',
    'W_B_C___m_a_x': 'WBC_max',
    'W_B_C___m_i_n': 'WBC_min',
    'W_B_C___c_o_u_n_t': 'WBC_count',
    'P_l_a_t_e_l_e_t_s___m_e_a_n': 'Platelets_mean',
    'P_l_a_t_e_l_e_t_s___s_t_d': 'Platelets_std',
    'P_l_a_t_e_l_e_t_s___m_a_x': 'Platelets_max',
    'P_l_a_t_e_l_e_t_s___m_i_n': 'Platelets_min',
    'P_l_a_t_e_l_e_t_s___c_o_u_n_t': 'Platelets_count',
    'P_T_T___m_e_a_n': 'PTT_mean',
    'P_T_T___s_t_d': 'PTT_std',
    'P_T_T___m_a_x': 'PTT_max',
    'P_T_T___m_i_n': 'PTT_min',
    'P_T_T___c_o_u_n_t': 'PTT_count',
    'F_i_b_r_i_n_o_g_e_n___m_e_a_n': 'Fibrinogen_mean',
    'F_i_b_r_i_n_o_g_e_n___s_t_d': 'Fibrinogen_std',
    'F_i_b_r_i_n_o_g_e_n___m_a_x': 'Fibrinogen_max',
    'F_i_b_r_i_n_o_g_e_n___m_i_n': 'Fibrinogen_min',
    'F_i_b_r_i_n_o_g_e_n___c_o_u_n_t': 'Fibrinogen_count',
    'F_i_O_2___m_e_a_n': 'FiO2_mean',
    'F_i_O_2___s_t_d': 'FiO2_std',
    'F_i_O_2___m_a_x': 'FiO2_max',
    'F_i_O_2___m_i_n': 'FiO2_min',
    'F_i_O_2___c_o_u_n_t': 'FiO2_count',
    'p_H___m_e_a_n': 'pH_mean',
    'p_H___s_t_d': 'pH_std',
    'p_H___m_a_x': 'pH_max',
    'p_H___m_i_n': 'pH_min',
    'p_H___c_o_u_n_t': 'pH_count',
    'P_a_C_O_2___m_e_a_n': 'PaCO2_mean',
    'P_a_C_O_2___s_t_d': 'PaCO2_std',
    'P_a_C_O_2___m_a_x': 'PaCO2_max',
    'P_a_C_O_2___m_i_n': 'PaCO2_min',
    'P_a_C_O_2___c_o_u_n_t': 'PaCO2_count',
}

In [50]:
dfA_final.rename(columns = (rename_dictionary), inplace = True)

In [53]:
dfA_final.info(verbose = True, show_counts = True)

<class 'pandas.core.frame.DataFrame'>
Index: 20336 entries, p000001.psv to p020643.psv
Data columns (total 135 columns):
 #    Column            Non-Null Count  Dtype
---   ------            --------------  -----
 0    HR_mean           20335 non-null  float64
 1    HR_std            20330 non-null  float64
 2    HR_max            20335 non-null  float64
 3    HR_min            20335 non-null  float64
 4    HR_count          20336 non-null  int64
 5    O2Sat_mean        20324 non-null  float64
 6    O2Sat_std         20314 non-null  float64
 7    O2Sat_max         20324 non-null  float64
 8    O2Sat_min         20324 non-null  float64
 9    O2Sat_count       20336 non-null  int64
 10   Temp_mean         20101 non-null  float64
 11   Temp_std          19861 non-null  float64
 12   Temp_max          20101 non-null  float64
 13   Temp_min          20101 non-null  float64
 14   Temp_count        20336 non-null  int64
 15   SBP_mean          20078 non-null  float64
 16   SBP_std           20018 non-null  float64
 17   SBP_max           20078 non-null  float64
 18   SBP_min           20078 non-null  float64
 19   SBP_count         20336 non-null  int64
 20   MAP_mean          20334 non-null  float64
 21   MAP_std           20326 non-null  float64
 22   MAP_max           20334 non-null  float64
 23   MAP_min           20334 non-null  float64
 24   MAP_count         20336 non-null  int64
 25   DBP_mean          12952 non-null  float64
 26   DBP_std           12773 non-null  float64
 27   DBP_max           12952 non-null  float64
 28   DBP_min           12952 non-null  float64
 29   DBP_count         20336 non-null  int64
 30   Resp_mean         20308 non-null  float64
 31   Resp_std          20285 non-null  float64
 32   Resp_max          20308 non-null  float64
 33   Resp_min          20308 non-null  float64
 34   Resp_count        20336 non-null  int64
 35   BaseExcess_mean   12652 non-null  float64
 36   BaseExcess_std    10924 non-null  float64
 37   BaseExcess_max    12652 non-null  float64
 38   BaseExcess_min    12652 non-null  float64
 39   BaseExcess_count  20336 non-null  int64
 40   HCO3_mean         19801 non-null  float64
 41   HCO3_std          15941 non-null  float64
 42   HCO3_max          19801 non-null  float64
 43   HCO3_min          19801 non-null  float64
 44   HCO3_count        20336 non-null  int64
 45   Lactate_mean      7733 non-null   float64
 46   Lactate_std       5090 non-null   float64
 47   Lactate_max       7733 non-null   float64
 48   Lactate_min       7733 non-null   float64
 49   Lactate_count     20336 non-null  int64
 50   Glucose_mean      19929 non-null  float64
 51   Glucose_std       16572 non-null  float64
 52   Glucose_max       19929 non-null  float64
 53   Glucose_min       19929 non-null  float64
 54   Glucose_count     20336 non-null  int64
 55   BUN_mean          19909 non-null  float64
 56   BUN_std           16109 non-null  float64
 57   BUN_max           19909 non-null  float64
 58   BUN_min           19909 non-null  float64
 59   BUN_count         20336 non-null  int64
 60   Creatinine_mean   19875 non-null  float64
 61   Creatinine_std    14975 non-null  float64
 62   Creatinine_max    19875 non-null  float64
 63   Creatinine_min    19875 non-null  float64
 64   Creatinine_count  20336 non-null  int64
 65   Calcium_mean      16547 non-null  float64
 66   Calcium_std       10616 non-null  float64
 67   Calcium_max       16547 non-null  float64
 68   Calcium_min       16547 non-null  float64
 69   Calcium_count     20336 non-null  int64
 70   Chloride_mean     19794 non-null  float64
 71   Chloride_std      15938 non-null  float64
 72   Chloride_max      19794 non-null  float64
 73   Chloride_min      19794 non-null  float64
 74   Chloride_count    20336 non-null  int64
 75   Magnesium_mean    18948 non-null  float64
 76   Magnesium_std     14870 non-null  float64
 77   Magnesium_max     18948 non-null  float64
 78   Magnesium_min     18948 non-null  float64
 79   Magnesium_count   20336 non-null  int64
 80   Phosphate_mean    16686 non-null  float64
 81   Phosphate_std     10766 non-null  float64
 82   Phosphate_max     16686 non-null  float64
 83   Phosphate_min     16686 non-null  float64
 84   Phosphate_count   20336 non-null  int64
 85   Potassium_mean    19903 non-null  float64
 86   Potassium_std     16904 non-null  float64
 87   Potassium_max     19903 non-null  float64
 88   Potassium_min     19903 non-null  float64
 89   Potassium_count   20336 non-null  int64
 90   Hct_mean          19972 non-null  float64
 91   Hct_std           17365 non-null  float64
 92   Hct_max           19972 non-null  float64
 93   Hct_min           19972 non-null  float64
 94   Hct_count         20336 non-null  int64
 95   Hgb_mean          19829 non-null  float64
 96   Hgb_std           16079 non-null  float64
 97   Hgb_max           19829 non-null  float64
 98   Hgb_min           19829 non-null  float64
 99   Hgb_count         20336 non-null  int64
 100  WBC_mean          19711 non-null  float64
 101  WBC_std           15410 non-null  float64
 102  WBC_max           19711 non-null  float64
 103  WBC_min           19711 non-null  float64
 104  WBC_count         20336 non-null  int64
 105  Platelets_mean    19751 non-null  float64
 106  Platelets_std     14789 non-null  float64
 107  Platelets_max     19751 non-null  float64
 108  Platelets_min     19751 non-null  float64
 109  Platelets_count   20336 non-null  int64
 110  PTT_mean          15840 non-null  float64
 111  PTT_std           9368 non-null   float64
 112  PTT_max           15840 non-null  float64
 113  PTT_min           15840 non-null  float64
 114  PTT_count         20336 non-null  int64
 115  Fibrinogen_mean   2567 non-null   float64
 116  Fibrinogen_std    1170 non-null   float64
 117  Fibrinogen_max    2567 non-null   float64
 118  Fibrinogen_min    2567 non-null   float64
 119  Fibrinogen_count  20336 non-null  int64
 120  FiO2_mean         11987 non-null  float64
 121  FiO2_std          11196 non-null  float64
 122  FiO2_max          11987 non-null  float64
 123  FiO2_min          11987 non-null  float64
 124  FiO2_count        20336 non-null  int64
 125  pH_mean           13181 non-null  float64
 126  pH_std            11268 non-null  float64
 127  pH_max            13181 non-null  float64
 128  pH_min            13181 non-null  float64
 129  pH_count          20336 non-null  int64
 130  PaCO2_mean        12577 non-null  float64
 131  PaCO2_std         10459 non-null  float64
 132  PaCO2_max         12577 non-null  float64
 133  PaCO2_min         12577 non-null  float64
 134  PaCO2_count       20336 non-null  int64
dtypes: float64(108), int64(27)
memory usage: 21.1+ MB

In [54]:
dfA_final

,HR_mean,HR_std,HR_max,HR_min,HR_count,O2Sat_mean,O2Sat_std,O2Sat_max,O2Sat_min,O2Sat_count,...,pH_mean,pH_std,pH_max,pH_min,pH_count,PaCO2_mean,PaCO2_std,PaCO2_max,PaCO2_min,PaCO2_count
patient_id,,,,,,,,,,,,,,,,,,,,,
p000001.psv,101.571429,9.594378,117.0,76.0,49,91.477273,3.460667,100.0,85.0,44,...,7.347143,0.031472,7.40,7.31,7,95.333333,6.022181,100.0,86.0,6
p000002.psv,60.954545,8.144395,94.0,54.0,22,97.000000,2.138090,100.0,94.0,22,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p000003.psv,79.611111,6.714036,93.0,68.0,45,95.431818,1.655122,99.0,91.0,44,...,7.496667,0.011547,7.51,7.49,3,39.500000,2.121320,41.0,38.0,2
p000004.psv,102.444444,6.337212,113.0,93.0,27,98.203704,1.449531,100.0,95.5,27,...,7.390000,0.026458,7.41,7.36,3,43.000000,2.828427,45.0,41.0,2
p000005.psv,73.916667,7.586697,88.0,61.0,24,97.500000,0.741620,99.0,96.0,21,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
p020639.psv,87.420000,12.475543,120.0,74.0,25,98.940000,0.982344,100.0,97.0,25,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p020640.psv,80.920000,7.425575,96.0,71.0,25,95.620000,1.861227,100.0,93.0,25,...,7.358333,0.059470,7.43,7.26,6,37.900000,3.577709,44.0,35.0,5
p020641.psv,85.900000,7.281194,101.5,76.0,20,97.023810,1.874008,99.0,94.0,21,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0
p020642.psv,96.525000,11.602359,130.0,79.0,40,99.512821,0.942332,100.0,96.0,39,...,7.450000,0.000000,7.45,7.45,2,34.000000,NaN,34.0,34.0,1
p020643.psv,94.448276,15.204760,140.0,79.0,29,97.178571,2.211980,100.0,88.0,28,...,7.374000,0.124820,7.48,7.16,5,45.200000,12.657014,67.0,34.0,5